### ISSUE TITLE
前端提交的json数据,id等数值型数据为字符串形式如何校验

### ISSUE THREAD

**Issue by banduoba** [ausaki/python-validator#2]
请问如下校验规则:
`cat_id = IntegerField(min_value=1, max_value=100)`
前端传入的值为
```json
data = {
    'cat_id':'12'
}
```
正常是校验通过,此处校验失败。
请问如何解决.

**Comment by ausaki** [comment]
添加`strict=False`参数：`cat_id = IntegerField(min_value=1, max_value=100, strict=False)`。

参考：[字段 API](https://ausaki.github.io/python-validator/fields/#basefield)

**Comment by banduoba** [comment]
谢谢
