### ISSUE TITLE
异常信息如何返回给前端

### ISSUE THREAD

**Issue by banduoba** [ausaki/python-validator#3]
通过 try 捕获错误信息,ParameterException不过一直无法返回到前端,请问如何操作谢谢,刚刚学 python 不久,希望可以解答;
尝试过`return ParameterException(data=v.str_errors)`
```python
form_data = request.json
    v = TaskValidator(form_data)
    try:
        v.is_valid(form_data)
    except ValueError:
        ParameterException(data=v.str_errors)
```

`ParameterExceptio`
```python
class ParameterException(APIException):
    code = 400
    msg = "invalid parameter"
    error_code = 1000
    data = {}
```
`APIException`
```python
class APIException(HTTPException):
    code = 500
    msg = "sorry,we make a mistake!"
    error_code = 999
    data = {}

    def __init__(self, msg=None, code=None, error_code=None, data=None, headers=None):
        if code:
            self.code = code

        if error_code:
            self.error_code = error_code

        if msg:
            self.msg = msg
        if data:
            self.data = data

        super(APIException, self).__init__(msg, None)

    def get_body(self, environ=None):
        body = dict(
            msg=self.msg,
            error_code=self.error_code,
            request=request.method + " " + self.get_url_no_param(),
            data=self.data
        )

        text = json.dumps(body)

        return text

    def get_headers(self, environ=None):
        return [("Content-Type", "application/json")]

    @staticmethod
    def get_url_no_param():
        full_path = request.full_path
        main_path = full_path.split("?")

        return main_path[0]
```

**Comment by banduoba** [comment]
上面只要校验信息不通过,终端就会打印出错误信息,希望知道如何把这个错误信息返回到前端

**Comment by banduoba** [comment]
![image](https://user-images.githubusercontent.com/4811366/52991983-eaea6e80-3449-11e9-8e61-259c2afdc671.png)

**Comment by ausaki** [comment]
可以先看一遍python-validator的[文档](https://ausaki.github.io/python-validator)。

回到你的问题，返回异常信息给前端可以参考下面的代码：

```py
form_data = request.json
v = TaskValidator(form_data)
# 注意：v.is_valid方法接受一个参数raise_error，如果raise_error为True，如果数据非法，则会
# 抛出异常。如果raise_error为False，则不会抛出异常，可以通过返回值判断数据是否合法。
if not v.is_valid():
    return Response({'error_msg': v.str_errors}, status=400)
```

**Comment by banduoba** [comment]
> 可以先看一遍python-validator的[文档](https://ausaki.github.io/python-validator)。
> 
> 回到你的问题，返回异常信息给前端可以参考下面的代码：
> 
> ```python
> form_data = request.json
> v = TaskValidator(form_data)
> # 注意：v.is_valid方法接受一个参数raise_error，如果raise_error为True，如果数据非法，则会
> # 抛出异常。如果raise_error为False，则不会抛出异常，可以通过返回值判断数据是否合法。
> if not v.is_valid():
>     return Response({'error_msg': v.str_errors}, status=400)
> ```

参考这个了,在 if not.is_valid()这里直接就抛出异常了,程序执行不到`return Response({'error_msg': v.str_errors}, status=400)`这里

**Comment by banduoba** [comment]
> 可以先看一遍python-validator的[文档](https://ausaki.github.io/python-validator)。
> 
> 回到你的问题，返回异常信息给前端可以参考下面的代码：
> 
> ```python
> form_data = request.json
> v = TaskValidator(form_data)
> # 注意：v.is_valid方法接受一个参数raise_error，如果raise_error为True，如果数据非法，则会
> # 抛出异常。如果raise_error为False，则不会抛出异常，可以通过返回值判断数据是否合法。
> if not v.is_valid():
>     return Response({'error_msg': v.str_errors}, status=400)
> ```

参考这个了,在 if not.is_valid()这里直接就抛出异常了,程序执行不到`return Response({'error_msg': v.str_errors}, status=400)`这里

**Comment by banduoba** [comment]
`task_id = IntegerField(min_value=1, max_value=10000, strict=False, default='')`
另外我这边前端`task_id`没有值传来,默认直接为空字符'',提示报错如下
`validator.exceptions.ValidationError: {'task_id': "type convertion(str -> integer) is failed: invalid literal for int() with base 10: ''"}`
这种情况文档里面没有看到

**Comment by banduoba** [comment]
文档昨天到今天看了3遍了,没找到解决思路

**Comment by banduoba** [comment]
> `task_id = IntegerField(min_value=1, max_value=10000, strict=False, default='')`
> 另外我这边前端`task_id`没有值传来,默认直接为空字符'',提示报错如下
> `validator.exceptions.ValidationError: {'task_id': "type convertion(str -> integer) is failed: invalid literal for int() with base 10: ''"}`
> 这种情况文档里面没有看到

刚刚又仔细看了下文档,这个好像通过`自定义字段`可以解决是吧

**Comment by ausaki** [comment]
> 参考这个了,在 if not.is_valid()这里直接就抛出异常了,程序执行不到`return Response({'error_msg': v.str_errors}, status=400)`这里

注意你的代码中是给`is_valid`传了一个参数的：
```py
if not form_v.is_valid(form_data)
```
如果raise_error=True，且数据不合法，is_valid方法就会抛出异常。

**Comment by ausaki** [comment]
> `task_id = IntegerField(min_value=1, max_value=10000, strict=False, default='')`
> 另外我这边前端`task_id`没有值传来,默认直接为空字符'',提示报错如下
> `validator.exceptions.ValidationError: {'task_id': "type convertion(str -> integer) is failed: invalid literal for int() with base 10: ''"}`
> 这种情况文档里面没有看到

这里的校验流程是这样的：
1. 发现`data`里面没有`task_id`，则使用默认值`''`(空字符串)
2. 检查数据类型，因为`strict=False`，所以尝试将`''`转换为`int`，转换失败就抛出异常了。

最好将`default`设置为同类型的值，例如`default=0`

**Comment by banduoba** [comment]
> > 参考这个了,在 if not.is_valid()这里直接就抛出异常了,程序执行不到`return Response({'error_msg': v.str_errors}, status=400)`这里
> 
> 注意你的代码中是给`is_valid`传了一个参数的：
> 
> ```python
> if not form_v.is_valid(form_data)
> ```
> 
> 如果raise_error=True，且数据不合法，is_valid方法就会抛出异常。

多传了一个参数,确实这里我弄错了

**Comment by ausaki** [comment]
Close issue
