### ISSUE TITLE
只能用于django框架吗？

### ISSUE THREAD

**Issue by yunweiguo** [ausaki/python-validator#6]
我想用于 tornado 框架，但是提示 django.core.exceptions.ImproperlyConfigured: Requested setting USE_I18N, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

**Comment by ausaki** [comment]
应该是[translations.py](https://github.com/ausaki/python-validator/blob/a3e591b1eae6d7a70f894c203dbd7195f929baa8/validator/translation.py#L21)出错了。

你的Python环境中应该安装了Django，但是python-validator所在的项目并不是Django的项目，所以出现了上述异常。你试试卸载Django。

**Comment by yunweiguo** [comment]
确实是translations.py 出错，删除 django就没问题了。 感谢
