### ISSUE TITLE
 可不可以自定义 str_errors 呢？

### ISSUE THREAD

**Issue by saya886** [ausaki/python-validator#8]
可不可当验证数据失败后 返回自定义的 错误信息呢？

**Comment by ausaki** [comment]
无法直接自定义错误信息. 这个库只负责校验大多数常见的非法数据, 如果想要校验特殊的数据格式, 推荐继承 `xxxField` 类, 实现自定义的校验逻辑, 或者重写 `Validator.validate_xxx()` 方法.

详细看[这里](https://ausaki.github.io/python-validator/advanced/#_4)和[这里](https://ausaki.github.io/python-validator/custom_field/).

**Comment by saya886** [comment]
谢谢
